name: CI/CD Pipeline to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Cache Next.js cache
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-

    - name: Disable Next.js telemetry
      run: npx next telemetry disable

    - name: Update Browserslist DB
      run: npx update-browserslist-db@latest

    - name: Install dependencies
      run: npm install

    - name: Build Next.js application
      run: npm run build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Remove existing files in the web directory
          sudo rm -rf /opt/bitnami/apache/htdocs/*
          
          # Remove index.html specifically
          sudo rm -f /opt/bitnami/apache/htdocs/index.html
          
          # Copy the built Next.js files to the web directory
          sudo cp -r ${{ github.workspace }}/.next/* /opt/bitnami/apache/htdocs/
          
          # Set proper permissions
          sudo chown -R bitnami:bitnami /opt/bitnami/apache/htdocs
          
          # Restart Apache to apply changes
          sudo /opt/bitnami/ctlscript.sh restart apache
